# Generated by Django 4.2.4 on 2023-08-11 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='task_descrition',
            new_name='task_description',
        ),
    ]
